version: "3"

services:

  app:
    build: ./app
    env_file:
      - ./.env
    depends_on:
      - "db"
    command: ["/usr/src/app/wait-for", "db:5432", "--", "python", "app.py"]

  db:
    image: postgres:10-alpine
    env_file:
      - ./.env
