version: "3"

services:

  app:
    build: ./app
    env_file:
      - ./.env
    depends_on:
      - "db"
    command: ["/usr/src/app/wait-for", "db:5432", "--", "python", "app.py"]
    restart: always

  db:
    image: postgres:10-alpine
    env_file:
      - ./.env
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
