name: Run on demand

# Controls when the action will run
on:
  # Triggers the workflow whenever the comment "OK to test" is added in a PR (which is internally seen as a type of issue by GitHub)
  issue_comment:
    types: [created, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ondemand"
  ondemand:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: github.event.comment.body == 'OK to test'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Creates a .env file from the example one
      -  name: Create environment file
         run: cp ./.env.example ./.env

      # Runs docker-compose using the runners shell
      - name: Build and start
        run: docker-compose up -d app

      # Lists all containers, including stopped ones
      - name: Check running containers
        run: docker ps -a

      # Shows container logs
      - name: Logs
        run: docker-compose logs app
